export const ADD_BOOK_DESCRIBTION = 'ADD_BOOK_DESCRIBTION';
export const EDIT_BOOK_DESCRIBTION = 'EDIT_BOOK_DESCRIBTION';
export const DELETE_BOOK_DESCRIBTION = 'DELETE_BOOK_DESCRIBTION';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
